# ~/.config/starship.toml

# prompt format
format = """
[╭──](bold gray)[⟰](bold green) $directory [(<$git_branch$git_status>)](bold yellow) [$status](bold red)
[╰─](bold gray)$character"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
truncation_length=0
truncate_to_repo=false
style="bold blue"

[character]
success_symbol="[⧁](bold gray)"
error_symbol="[⮿](bold red)"

[git_branch]
format="[$branch](bold yellow)"


[git_status]
format="[$modified](bold yellow)"
modified="*"

[status]
disabled=false
format="$int$symbol"
symbol="↵"
